image: node:16-alpine

variables:
  VERSION: 0.0.1

stages:
  - install
  - test
  - deploy

cache:
  key: ${CI_COMMIT_REF_SLUG}
  paths:
  - node_modules/
  - .npm/

install_dependencies:
  stage: install
  script:
    - npm ci --cache .npm --prefer-offline

eslint:
  stage: test
  script: npm run lint

unit_tests:
  stage: test
  before_script:
    - apk add chromium
    - export CHROME_BIN=/usr/bin/chromium-browser
  script: npm run test-ci
