image: node:16-alpine

variables:
  VERSION: 0.0.1

stages:
  - install
  - test
  - deploy

cache:
  key: ${CI_COMMIT_REF_SLUG}
  paths:
  - node_modules/
  - .npm/

install_dependencies:
  stage: install
  script:
    - npm ci --cache .npm --prefer-offline

unit_tests:
  stage: test
  script: echo "Tests will happen here..."

pages:
  stage: deploy
  script:
    - npm run gl-pages
  artifacts:
    paths:
      - public
