image: alpine:latest

variables:
  VERSION: 0.0.1

stages:
  - test
  - deploy

unit_tests:
  stage: test
  script: echo "Tests will happen here..."

pages:
  stage: deploy_demo
  script:
    - npm run gl-pages
  artifacts:
    paths:
      - public
